[sitedenolan]
keepalive_timeout = 30
max_request_size = 65536
listen = "0.0.0.0:8080"
locations = { "/" = "./examples/nolan", "/tmp" = "/tmp" }
document_index = index.html
error_pages = { 404 = "404.html", 429 = "429.html"}
allowed_methods = ["GET", "POST"]
redirections = { "/redirection1" = "https://youtube.com/", "/redirection2" = "https://instagram.com/" }
directory_listing_enabled = true
file_on_directory = "/path/to/file_on_directory.html"
file_upload_enabled = true
file_upload_directory = "/path/to/upload_directory"
cgi_enabled = true
cgi = {".js" = "/bin/nodejs"}

[sitedeetienne]
keepalive_timeout = 15
max_request_size = 32768
listen = "0.0.0.0:6767"
locations = { "/" = "./examples/etienne", "/tmp" = "/tmp" }
document_index = index.html
error_pages = { 404 = "404.html", 429 = "429.html"}
allowed_methods = ["GET", "POST"]
redirections = { "/fortnite" = "https://fortnite.com/", "/roblox" = "https://roblox.com/" }
directory_listing_enabled = true
file_on_directory = "/path/to/file_on_directory.html"
file_upload_enabled = false
file_upload_directory = "/path/to/upload_directory"
cgi_enabled = true
cgi = {".py" = "/bin/python"}